port: 4000
highlighter: true
permalink: pretty
title: "A blog of Nikita Barsukov"
description: "Gallery of my data analysis projects, and other things that I'm interested in"
gems:
  - jekyll-redirect-from
  - jekyll-sitemap
tag_page_layout: tag_page
tag_page_dir: tag
exclude: [README.md, Gemfile, Gemfile.lock, config.ru, CNAME, unicorn.rb, Procfile, vendor]
