port: 4000
permalink: pretty
title: "A blog of Nikita Barsukov"
description: "Gallery of my data analysis projects, and other things that I'm interested in"
gems:
  - jekyll-redirect-from
  - jekyll-sitemap
  