port: 4000
highlighter: true
permalink: pretty
title: "A blog of Nikita Barsukov"
description: "Gallery of my data analysis projects, and other things that I'm interested in"
gems:
  - jekyll-redirect-from
  - jekyll/tagging
tag_page_layout: tag_page
tag_page_dir: tag
